server:
  port: 80

spring:
  jackson:
    time-zone: GMT+8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
     add-mappings: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        min-idle: 1
        max-active: 5000
        max-idle: 5000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seagox?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    solr:
      host: http://127.0.0.1:8983/solr/solr_core


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.seagox.oa
  global-config.db-config.id-type: AUTO # oracle 配置INPUT
  type-handlers-package: com.seagox.oa.common

#oracle不加报错
#  configuration:
#    jdbc-type-for-null: 'null'

logging:
  file:
    path: /usr/logging
  pattern:
    console: "%d - %msg%n"
  level:
    com:
      seagox:
        oa: debug

# 1:minio 2:aliyun 3:ecloud、aws s3
oss:
  type: 1
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin

#Windows G:\\workingdir
#Linux /opt/workingdir
#LibreOffice
jodconverter:
  working-dir: G:\\workingdir
  
third-party:
  applets:
    appid: wx78df
    sercret: 0db176c
  serviceNumber:
    appid: wx78df
    sercret: 0db176c
    
ignore:
  secret: 61e2znsKMY75Q9YjaI4719xHJcllvMRy
  token: /auth,/upload,/cloud/entrance,/cloud/download
  sign: /auth,/upload,/user/import,/cloud/download,/cloud/entrance/openApi

#人大金仓数据库要配置postgresql
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

#sqlserver
#url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=localdemo
#driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

#kingbase8
#url: jdbc:kingbase8://127.0.0.1:54321/oa?stringtype=unspecified
#driver-class-name: com.kingbase8.Driver

#postgresql
#url: jdbc:postgresql://127.0.0.1:5432/oa?stringtype=unspecified
#driver-class-name: org.postgresql.Driver

#oracle
#url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
#driver-class-name: oracle.jdbc.OracleDriver

#dm
#url: jdbc:dm://127.0.0.1:5236/oa?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#driver-class-name: dm.jdbc.driver.DmDriver

#mysql
#url: jdbc:mysql://127.0.0.1:3306/oa?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
#driver-class-name: com.mysql.cj.jdbc.Driver
